### ISSUE TITLE
Eigendecomposition

### ISSUE THREAD

**Issue by n1kn4x** [srom/cma-es#1]
Hey,

Sometimes in my experiments the eigendecomposition fails when the initial state is chosen poorly.
Wouldn't it make sense to use the SVD instead of the eigendecomposition?

Cheers

**Comment by n1kn4x** [comment]
So instead of computing (cma/core.py):
  0             try:
  1                 eigenvalues, eigenvectors = tf.linalg.eigh(C)
  2             except tf.errors.InvalidArgumentError as e:
  3                 logger.error(e)
  4                 logger.error('Eigen decomposition was not successful - aborting')
  5                 break
  6 
  7             diag_D = tf.sqrt(eigenvalues)
  8             D = tf.linalg.tensor_diag(diag_D)
  9             B = eigenvectors

We write:
  0             diag_D, B, _ = tf.linalg.svd(C)
  1             D = tf.linalg.tensor_diag(diag_D)

**Comment by srom** [comment]
Indeed I've noticed some instability in my experimentations too. That's why I added a try catch statement around `tf.linalg.eigh`.

I've noticed that you implemented your fix: https://github.com/n1kn4x/cma-es/commit/f98622368f5ca136e53758c6a648dec1e6db4348

Would you care to open a PR? If the tests pass I am keen to merge your changes.

Cheers

**Comment by srom** [comment]
Done and merged. Thank you for your help!

https://github.com/srom/cma-es/releases/tag/v1.3.0
